Develop mdl 21 course creation
elaastic/elaastic-questions-server pull request #106
Opened 2021-02-24 14:54 UTC by Shinooow

Fin développement user story "creation of a course" #10

2021-02-24 15:07 UTC, Shinooow commented
La visualisation des cours pour un enseignant est aussi disponible sur la branche course-creation puisque nous avons eu besoin de la visualisation pour tester la création.

2021-02-24 17:01 UTC, BrunoPicolo commented on src/main/kotlin/org/elaastic/questions/course/Course.kt
> +    /*To add in a later version*/
Personnellement je trouve que c'est hors contexte ajouter du code commenté.
A enlever ou décommenter.

2021-02-24 17:13 UTC, BrunoPicolo commented on src/main/kotlin/org/elaastic/questions/course/CourseRepository.kt
> +    fun findOneById(id: Long): Course
La méthode findOneById est seulement présente dans le repository et le Service. Si ce n'est pas utilisé par le controlleur ni par les tests, la méthode est hors le périmètre de la pull request.
Pour l'instant c'est du code mort.

2021-02-24 17:18 UTC, BrunoPicolo commented on src/main/kotlin/org/elaastic/questions/subject/Subject.kt
> +        var parentSubject: Subject? = null,
Je n'ai pas en tête tout le code, mais maintenant qu'on garde les sujets dans des cours. 
Est-ce que le paramètre parentSubjet est nécessaire ?  A quoi servait il ? A quoi sert il maintenant ?

2021-02-24 17:26 UTC, BrunoPicolo reviewed
En regardant rapidement le code, je pense que vous avez fait un bon travail. Il faut rester dans le périmètre de la fonctionnalité, donc à éviter d'ajouter du code commenté ou du code que vous n'utilisez pas.

2021-02-24 17:41 UTC, 422404 commented on src/main/kotlin/org/elaastic/questions/course/Course.kt
> +    /*To add in a later version*/
En effet, je ne trouve pas ça génial non plus. Vous pourriez le garder au chaud de votre côté mais les sources ne sont pas l'endroit le plus sympa où le garder.

2021-02-24 17:43 UTC, 422404 commented on src/main/kotlin/org/elaastic/questions/course/Course.kt
> +    /*To add in a later version*/
Après, vu que la classe Subject existe déjà, vous pouvez très bien le décommenter.

2021-02-24 17:54 UTC, 422404 commented on src/main/kotlin/org/elaastic/questions/course/CourseRepository.kt
> +    fun findOneById(id: Long): Course
Pour ma part, je suis moins catégorique. Autant le code commenté n'est pas super mais là c'est la signature d'une méthode dans une interface. Cette méthode sera forcément utilisée. Je le vois davantage comme faisant partie des méthodes de base à définir dans un repository et un service.

2021-02-24 17:56 UTC, 422404 commented on src/main/kotlin/org/elaastic/questions/course/CourseController.kt
> +        if (!model.containsAttribute("course")) {
Il est possible que l'attribut existe déjà ?

2021-02-24 17:58 UTC, 422404 commented on src/main/resources/db/migration/V29__Add_Course.sql
> +/*ALTER TABLE `subject`
Même réflexion que pour l'autre code commenté. Celui-ci doit être supprimé.

2021-02-24 18:01 UTC, 422404 commented on src/main/resources/templates/course/_course_form.html
> +        <!-- <input type="text"
Ce code pourra être trivialement réécrit.

PS: fallait que je case "trivial"
PPS: Désolé, vous devez croire qu'on part en croisade contre le code mort x)

2021-02-24 18:07 UTC, 422404 commented on src/main/resources/templates/course/index.html
> +                <!--
Pareil ici.

2021-02-24 18:09 UTC, 422404 commented on src/main/resources/templates/i18n/course_es.properties
> +course.title.label=Nuevo course
"courso"
Bruno l'a même pas capté x)

2021-02-24 18:10 UTC, 422404 commented on src/main/resources/templates/i18n/course_es.properties
> +course.creation.label=Course Creation
Hésitez pas à demander à Bruno pour les quelques traductions supplémentaires :)

2021-02-24 18:17 UTC, 422404 requested changes
Ce n'est pas au nombre de remarques que vous êtes évalués, donc ne vous inquiétez pas. Le volume de code n'est pas énorme mais de ce que je peux voir vous codez proprement.
C'est bien, keep up the good work 💪

2021-02-24 18:27 UTC, RemakeTm commented on src/main/kotlin/org/elaastic/questions/course/Course.kt
> +    /*To add in a later version*/
C'était un morceau de code qui date un peu que j'ai gardé le temps de savoir si oui ou non il avait sa place en me disant qu'il l'aurait trouvé avant les merges (un peu naïf). Mais en effet il aurait pas du atterrir si loin, à régler

2021-02-24 18:33 UTC, RemakeTm commented on src/main/kotlin/org/elaastic/questions/subject/Subject.kt
> +        var parentSubject: Subject? = null,
A vrai dire on ne nous a jamais vraiment parlé de Sujets parents d'autres Sujet donc on a fait abstraction. Mais en effet si le nom traduit bel et bien ce qu'il veut dire, il est obsolète avec la nouvelle notion de cours

2021-02-24 18:35 UTC, RemakeTm commented on src/main/kotlin/org/elaastic/questions/course/CourseController.kt
> +        if (!model.containsAttribute("course")) {
Dans la mesure où ce test était présent dans la création d'un Sujet et que ce sont deux entités "semblables", on a jugé pertinent de le mettre

2021-02-24 22:40 UTC, 422404 approved these changes

2021-02-25 15:28 UTC, merged

2021-02-25 15:46 UTC, BrunoPicolo commented on src/main/kotlin/org/elaastic/questions/subject/Subject.kt
> +        var parentSubject: Subject? = null,
Si vous avez temps de plus il serait intéressant de voir si c'est obsolète ou pas :)

2021-02-25 15:48 UTC, BrunoPicolo commented on src/main/resources/templates/i18n/course_es.properties
> +course.title.label=Nuevo course
😂  il faut utiliser "Nuevo curso"