Merge feature/react-on-draxo-feedback into developpe
elaastic/elaastic-questions-server pull request #235
Opened 2024-04-25 13:07 UTC by Francois389

#177 

# Result 

Here we can see tree different possibility :

1. A review that was hidden by the teacher
2. A review with the utility grade `Tout a fais d'accord` has been selected
3. A review for which we don't have the report button because the evaluation has no comment. 

![image](https://github.com/elaastic/elaastic-questions-server/assets/75416431/cf09ef28-4b9c-4acf-84ac-166c11cda44a)

There is the teacher side.
We can notice the button for hidding the evaluation

![image](https://github.com/elaastic/elaastic-questions-server/assets/75416431/03071c00-87fd-4b79-8ae7-80ef48564dba)

There is the report modal.
When the `Autre` checkbox is checked, we have to specify a comment

![image](https://github.com/elaastic/elaastic-questions-server/assets/75416431/a19d2429-dd87-482a-8e92-6b3af20c349a)

2024-05-02 12:23 UTC, FranckSilvestre requested changes
- there is no feedback after a student has submitted a report or a utility grade on a peer review (the given grade is no displayed after submission)
- the student loose the focus when he submits a report or a utility grade.
- the teacher loose the focus when hiding a peer grading

2024-05-02 12:43 UTC, FranckSilvestre commented on src/main/kotlin/org/elaastic/questions/assignment/sequence/interaction/response/ResponseService.kt
> +        return response.learner == user
TODO: modify the doc and rename the method: canModerateFeedbackOfResponse

2024-05-06 11:47 UTC, Francois389 commented on src/main/kotlin/org/elaastic/questions/assignment/sequence/interaction/response/ResponseService.kt
> +        return response.learner == user
the commit [e7712f9](https://github.com/elaastic/elaastic-questions-server/pull/235/commits/e7712f9b002a4a00f3b2294f2b35a1df0eba5e13) solved the issue...

2024-05-06 16:47 UTC, FranckSilvestre approved these changes

2024-05-06 16:47 UTC, FranckSilvestre commented on src/main/resources/templates/player/assignment/sequence/phase/evaluation/method/draxo/_draxo-show-list.html
> +        <div th:replace="player/assignment/sequence/phase/evaluation/method/draxo/_draxo-show::draxoShow(${model},${hideName}, ${canModeratePeerGrading}, ${canHidePeerGrading})"></div>
Processed after peer review

2024-05-06 16:49 UTC, merged