Feat/available on konsolidation
elaastic/elaastic-questions-server pull request #241
Opened 2024-05-19 15:28 UTC by RemiSaurel

2024-05-19 16:19 UTC, FranckSilvestre requested changes

2024-05-20 07:08 UTC, RemiSaurel commented on src/main/resources/templates/player/assignment/sequence/play-learner.html
> +          <a href="https://konsolidation.irit.fr" target="_blank">
![CleanShot 2024-05-20 at 09 03 53@2x](https://github.com/elaastic/elaastic-questions-server/assets/50367862/103744f1-0413-449b-bb19-aa314c77e27b)
The property doesn't exist + when I try to add it to the `application.properties`, the only way to get it on the `.html` file would be to change the model(s); I can't access the property directly from the `.html`file. Do you think it is worth or this is good enough for the limited use of it?

2024-05-20 07:56 UTC, FranckSilvestre commented on src/main/resources/templates/player/assignment/sequence/play-learner.html
> +          <a href="https://konsolidation.irit.fr" target="_blank">
You have several examples of the use of an application property directly in a thymleaf template, one of them here :
https://github.com/elaastic/elaastic-questions-server/blob/develop/src/main/resources/templates/player/assignment/sequence/components/_auto-reload.html
I think you can use the same apporach.

2024-05-20 10:22 UTC, RemiSaurel commented on src/main/resources/templates/player/assignment/sequence/play-learner.html
> +          <a href="https://konsolidation.irit.fr" target="_blank">
Fixed in [fba1212](https://github.com/elaastic/elaastic-questions-server/pull/241/commits/fba121234115c6470dad7c12f3661e61ca17d1ec)

I had weird issues on Gradle build. I cleaned the project and retried and it worked fine :)

2024-05-20 11:31 UTC, FranckSilvestre approved these changes

2024-05-20 11:34 UTC, merged